
# Automatically generated by /Users/csuftitan/Documents/cpsc-120-prompt-lab-08/.action/ccsrcutilities.py on 2023-10-24 17:26:23

TOPTARGETS = all clean spotless format lint header test unittest

SUBDIRS = $(wildcard part-?/.)

default all: all

$(TOPTARGETS): $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -f Makefile -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(SUBDIRS)

